displayName=Moon Overlay
author=CaptainPoko
description = Renders a custom moon object overlay with sidebar control customization features
tags=overlay,sky,moon,skybox,night,orbit
version=1.0
plugins=poko.moon.MoonPlugin
build=standard